---
version: '3.6'

services:
  home-control-monitor-hue:
    image: robjenks/home-control:monitor-agent-st-${DEPLOYMENT_VERSION}
    ports:
      - "14230:14230"
      - "14231:14231"
    environment:
      - INTERNAL_TOKEN
