home:
  rooms:
    - id: livingRoom
      name: "Living Room"

    - id: bedroom
      name: "Bedroom"

  devices:
    - id: "Living room Back Left"
      class: hue
      room: livingRoom

    - id: "Living room Top Left"
      class: hue
      room: livingRoom

    - id: "http://192.168.1.21"
      name: "Awair Living Room"
      class: awair
      room: livingRoom

    - id: "http://192.168.1.25"
      name: "Awair Bedroom"
      class: awair
      room: bedroom
