home:
  rooms:
    - id: livingRoom
      name: "Living Room"

    - id: bedroom
      name: "Bedroom"

    - id: hallway
      name: "Hallway"

  devices:
    - id: "Living room Back Left"
      class: hue
      room: livingRoom

    - id: "Living room Top Left"
      class: hue
      room: livingRoom

    - id: "http://192.168.1.21"
      name: "Awair Living Room"
      class: awair
      room: livingRoom

    - id: "http://192.168.1.25"
      name: "Awair Bedroom"
      class: awair
      room: bedroom

    - id: d39152db-b02a-47e2-9adf-1a63cb7b953d
      name: "Bedroom Sonos"
      class: st
      room: bedroom

    - id: 82d8fc36-7516-413b-bbb3-8f4a1e11a692
      name: "Front door sensor"
      class: st
      room: hallway
