home:
  rooms:
    - id: livingRoom
      name: Living Room

    - id: bedroom
      name: Bedroom

    - id: kitchen
      name: Kitchen

    - id: hallway
      name: Hallway

    - id: bathroom
      name: Bathroom

    - id: none
      name: None

  devices:
    - id: Living room Back Left
      class: hue
      room: livingRoom

    - id: Living room Top Left
      class: hue
      room: livingRoom

    - id: Living room Top Right
      class: hue
      room: livingRoom

    - id: Living room Back Right
      class: hue
      room: livingRoom

    - id: Lightstrip
      name: Living room light strip
      class: hue
      room: livingRoom

    - id: Living room lamp
      class: hue
      room: livingRoom

    - id: "http://192.168.1.21"
      name: Awair Living Room
      class: awair
      room: livingRoom

    - id: 21665446-334e-47fd-bebe-58fa9084b449
      name: Sonos Playbar
      class: st
      room: livingRoom

    - id: 6e85dde4-a5d3-4ec6-a128-98db4d9c5caa
      name: Sonos Surround 1
      class: st
      room: livingRoom

    - id: ad582b88-4b2e-4039-8808-cf96c0d4771e
      name: Sonos Surround 2
      class: st
      room: livingRoom

    - id: Bedroom Back Left
      class: hue
      room: bedroom

    - id: Bedroom Top Left
      class: hue
      room: bedroom

    - id: Bedroom Top Right
      class: hue
      room: bedroom

    - id: Bedroom Back Right
      class: hue
      room: bedroom

    - id: "http://192.168.1.25"
      name: Awair Bedroom
      class: awair
      room: bedroom

    - id: d39152db-b02a-47e2-9adf-1a63cb7b953d
      name: Bedroom Sonos
      class: st
      room: bedroom

    - id: ea91dd8a-f0c5-400d-943f-fbc828df28d6
      name: Neato Botvac
      class: st
      room: bedroom

    - id: 68d502c6-b32a-482a-9dcf-93b8b5b0ab81
      name: Kitchen lights
      class: st
      room: kitchen

    - id: 82d8fc36-7516-413b-bbb3-8f4a1e11a692
      name: Front door
      class: st
      room: hallway

    - id: 02487e15-4bd9-4026-9511-86e36f89f84c
      name: Motion Sensor
      class: st
      room: none

    - id: a4987b7c-0f38-4671-afe7-f997c4c0a10f
      name: Arrival Sensor
      class: st
      room: none

    - id: 28ac0a36-5e2e-4bca-bd98-c5663a05983c
      name: "Rob's iPhone"
      class: st
      room: none
