---
kind: Namespace
apiVersion: v1
metadata:
  name: home-control
  labels:
    name: home-control

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-awair
  template:
    metadata:
      labels:
        entity: home-control-monitor-awair
    spec:
      containers:
      - name: home-control-monitor-awair
        image: robjenks/home-control:monitor-agent-awair-latest
        ports:
        - name: service-port
          containerPort: 14210
          protocol: TCP
        - name: actuator-port
          containerPort: 14211
          protocol: TCP
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 3

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
spec:
  selector:
    entity: home-control-monitor-awair
  ports:
  - name: service-port
    port: 14210
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14211
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-hue
  template:
    metadata:
      labels:
        entity: home-control-monitor-hue
    spec:
      containers:
      - name: home-control-monitor-hue
        image: robjenks/home-control:monitor-agent-hue-latest
        ports:
        - name: service-port
          containerPort: 14220
          protocol: TCP
        - name: actuator-port
          containerPort: 14221
          protocol: TCP
        env:
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: hue-auth
              key: internal-token
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 3

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
spec:
  selector:
    entity: home-control-monitor-hue
  ports:
  - name: service-port
    port: 14220
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14221
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-st
  template:
    metadata:
      labels:
        entity: home-control-monitor-st
    spec:
      containers:
      - name: home-control-monitor-st
        image: robjenks/home-control:monitor-agent-st-latest
        ports:
        - name: service-port
          containerPort: 14230
          protocol: TCP
        - name: actuator-port
          containerPort: 14231
          protocol: TCP
        env:
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: st-auth
              key: internal-token
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 3

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
spec:
  selector:
    entity: home-control-monitor-st
  ports:
  - name: service-port
    port: 14230
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14231
    targetPort: actuator-port
    protocol: TCP

