---
kind: Namespace
apiVersion: v1
metadata:
  name: home-control
  labels:
    name: home-control


### Zookeeper
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-zookeeper
  namespace: home-control
  labels:
    entity: home-control-zookeeper
    entityType: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-zookeeper
  template:
    metadata:
      labels:
        entity: home-control-zookeeper
    spec:
      containers:
      - name: home-control-zookeeper
        image: cfei/zookeeper:latest-multiarch
        ports:
        - name: client-port
          containerPort: 2181
          protocol: TCP
        - name: follower-port
          containerPort: 2888
          protocol: TCP
        - name: leader-port
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOO_ID
          value: "1"
        - name: ZOO_PORT
          value: "2181"
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-zookeeper
  namespace: home-control
  labels:
    entity: home-control-zookeeper
spec:
  selector:
    entity: home-control-zookeeper
  ports:
  - name: client-port
    port: 2181
    targetPort: client-port
    protocol: TCP
  - name: follower-port
    port: 2888
    targetPort: follower-port
    protocol: TCP
  - name: leader-port
    port: 3888
    targetPort: leader-port
    protocol: TCP


### Kafka
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-kafka-brokers
  namespace: home-control
  labels:
    entity: home-control-kafka-brokers
    entityType: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-kafka-brokers
  template:
    metadata:
      labels:
        entity: home-control-kafka-brokers
    spec:  
      containers:
      - name: home-control-kafka-brokers
        image: cfei/kafka:latest-multiarch
        ports:
        - name: external-port
          containerPort: 9092
          protocol: TCP
        - name: internal-port
          containerPort: 29092
          protocol: TCP
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "home-control-zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://home-control-kafka-brokers:29092,EXTERNAL://home-control-kafka-brokers:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-kafka-brokers
  namespace: home-control
  labels:
    entity: home-control-kafka-brokers
    entityType: kafka-broker
spec:
  selector:
    entity: home-control-kafka-brokers
  ports:
  - name: external-port
    port: 9092
    targetPort: external-port
    protocol: TCP
  - name: internal-port
    port: 29092
    targetPort: internal-port
    protocol: TCP

# Aggregation
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
    entityType: aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-aggregation
  template:
    metadata:
      labels:
        entity: home-control-aggregation
    spec:
      containers:
      - name: home-control-aggregation
        image: robjenks/home-control-aggregation:latest
        ports:
        - name: service-port
          containerPort: 14200
          protocol: TCP
        - name: actuator-port
          containerPort: 14201
          protocol: TCP
        - name: metrics-port
          containerPort: 14202
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
spec:
  selector:
    entity: home-control-aggregation
  clusterIP: None       # Headless
  ports:
  - name: service-port
    port: 14200
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14201
    targetPort: actuator-port
    protocol: TCP
  - name: metrics-port
    port: 14202
    targetPort: metrics-port
    protocol: TCP

# Monitor (Awair)
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-awair
  template:
    metadata:
      labels:
        entity: home-control-monitor-awair
    spec:
      containers:
      - name: home-control-monitor-awair
        image: robjenks/home-control-monitor-agent-awair:latest
        ports:
        - name: service-port
          containerPort: 14210
          protocol: TCP
        - name: actuator-port
          containerPort: 14211
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
spec:
  selector:
    entity: home-control-monitor-awair
  ports:
  - name: service-port
    port: 14210
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14211
    targetPort: actuator-port
    protocol: TCP

# Monitor (Hue)
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-hue
  template:
    metadata:
      labels:
        entity: home-control-monitor-hue
    spec:
      containers:
      - name: home-control-monitor-hue
        image: robjenks/home-control-monitor-agent-hue:latest
        ports:
        - name: service-port
          containerPort: 14220
          protocol: TCP
        - name: actuator-port
          containerPort: 14221
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: hue-auth
              key: internal-token
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
spec:
  selector:
    entity: home-control-monitor-hue
  ports:
  - name: service-port
    port: 14220
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14221
    targetPort: actuator-port
    protocol: TCP

# Monitor (ST)
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-st
  template:
    metadata:
      labels:
        entity: home-control-monitor-st
    spec:
      containers:
      - name: home-control-monitor-st
        image: robjenks/home-control-monitor-agent-st:latest
        ports:
        - name: service-port
          containerPort: 14230
          protocol: TCP
        - name: actuator-port
          containerPort: 14231
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: st-auth
              key: internal-token
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
spec:
  selector:
    entity: home-control-monitor-st
  ports:
  - name: service-port
    port: 14230
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14231
    targetPort: actuator-port
    protocol: TCP

# App UI
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-app
  namespace: home-control
  labels:
    entity: home-control-app
    entityType: app
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-app
  template:
    metadata:
      labels:
        entity: home-control-app
    spec:
      containers:
      - name: home-control-app
        image: robjenks/home-control-app:latest
        ports:
        - name: http-port
          containerPort: 14800
          protocol: TCP
        env:
        - name: AGGREGATION_SERVICE_URL
          value: service/aggregation
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-app
  namespace: home-control
  labels:
    entity: home-control-app
spec:
  selector:
    entity: home-control-app
  clusterIP: None       # Headless
  ports:
  - name: http-port
    port: 14800
    targetPort: http-port
    protocol: TCP

# Ingress controller
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-control-ingress
  namespace: home-control
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-control-app
            port:
              number: 14800

# Grafana
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: home-control-grafana-pvc
#  namespace: home-control
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#
#---
#kind: Deployment
#apiVersion: apps/v1
#metadata:
#  name: home-control-grafana
#  namespace: home-control
#  labels:
#    entity: home-control-grafana
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      entity: home-control-grafana
#  template:
#    metadata:
#      labels:
#        entity: home-control-grafana
#        entityType: grafana
#    spec:
#      securityContext:
#        runAsUser: 0
#        fsGroup: 472
#        supplementalGroups:
#          - 0
#      containers:
#      - name: home-control-grafana
#        image: grafana/grafana:7.5.2
#        ports:
#        - containerPort: 3000
#          name: http-grafana
#          protocol: TCP
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /robots.txt
#            port: 3000
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 30
#          successThreshold: 1
#          timeoutSeconds: 2
#        livenessProbe:
#          failureThreshold: 3
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          tcpSocket:
#            port: 3000
#          timeoutSeconds: 1
#        resources:
#          requests:
#            cpu: 250m
#            memory: 750Mi
#        volumeMounts:
#        - mountPath: /var/lib/grafana
#          name: home-control-grafana-pv
#      nodeSelector:
#        host.specs: high
#      volumes:
#      - name: home-control-grafana-pv
#        persistentVolumeClaim:
#          claimName: home-control-grafana-pvc
#
#---
#kind: Service
#apiVersion: v1
#metadata:
#  name: home-control-grafana
#  namespace: home-control
#  labels:
#    entity: home-control-grafana
#spec:
#  selector:
#    entity: home-control-grafana
# # type: LoadBalancer
# # sessionAffinity: None
#  ports:
#  - port: 3000
#    protocol: TCP
#    targetPort: http-grafana
