---
kind: Namespace
apiVersion: v1
metadata:
  name: home-control
  labels:
    name: home-control

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-zookeeper
  namespace: home-control
  labels:
    entity: home-control-zookeeper
    entityType: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-zookeeper
  template:
    metadata:
      labels:
        entity: home-control-zookeeper
    spec:
      containers:
      - name: home-control-zookeeper
        image: cfei/zookeeper:latest-multiarch
        ports:
        - name: client-port
          containerPort: 2181
          protocol: TCP
        - name: follower-port
          containerPort: 2888
          protocol: TCP
        - name: leader-port
          containerPort: 3888
          protocol: TCP
        env:
        - name: ZOO_ID
          value: "1"
        - name: ZOO_PORT
          value: "2181"
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-zookeeper
  namespace: home-control
  labels:
    entity: home-control-zookeeper
spec:
  selector:
    entity: home-control-zookeeper
  ports:
  - name: client-port
    port: 2181
    targetPort: client-port
    protocol: TCP
  - name: follower-port
    port: 2888
    targetPort: follower-port
    protocol: TCP
  - name: leader-port
    port: 3888
    targetPort: leader-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-kafka-brokers
  namespace: home-control
  labels:
    entity: home-control-kafka-brokers
    entityType: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-kafka-brokers
  template:
    metadata:
      labels:
        entity: home-control-kafka-brokers
    spec:  
      containers:
      - name: home-control-kafka-brokers
        image: cfei/kafka:latest-multiarch
        ports:
        - name: external-port
          containerPort: 9092
          protocol: TCP
        - name: internal-port
          containerPort: 29092
          protocol: TCP
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "home-control-zookeeper:2181"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://home-control-kafka-brokers:29092,EXTERNAL://home-control-kafka-brokers:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-kafka-brokers
  namespace: home-control
  labels:
    entity: home-control-kafka-brokers
    entityType: kafka-broker
spec:
  selector:
    entity: home-control-kafka-brokers
  ports:
  - name: external-port
    port: 9092
    targetPort: external-port
    protocol: TCP
  - name: internal-port
    port: 29092
    targetPort: internal-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
    entityType: aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-aggregation
  template:
    metadata:
      labels:
        entity: home-control-aggregation
    spec:
      containers:
      - name: home-control-aggregation
        image: robjenks/home-control-aggregation:latest
        ports:
        - name: service-port
          containerPort: 14200
          protocol: TCP
        - name: actuator-port
          containerPort: 14201
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
spec:
  selector:
    entity: home-control-aggregation
  clusterIP: None       # Headless
  ports:
  - name: service-port
    port: 14200
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14201
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-awair
  template:
    metadata:
      labels:
        entity: home-control-monitor-awair
    spec:
      containers:
      - name: home-control-monitor-awair
        image: robjenks/home-control-monitor-agent-awair:latest
        ports:
        - name: service-port
          containerPort: 14210
          protocol: TCP
        - name: actuator-port
          containerPort: 14211
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
spec:
  selector:
    entity: home-control-monitor-awair
  ports:
  - name: service-port
    port: 14210
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14211
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-hue
  template:
    metadata:
      labels:
        entity: home-control-monitor-hue
    spec:
      containers:
      - name: home-control-monitor-hue
        image: robjenks/home-control-monitor-agent-hue:latest
        ports:
        - name: service-port
          containerPort: 14220
          protocol: TCP
        - name: actuator-port
          containerPort: 14221
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: hue-auth
              key: internal-token
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
spec:
  selector:
    entity: home-control-monitor-hue
  ports:
  - name: service-port
    port: 14220
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14221
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-st
  template:
    metadata:
      labels:
        entity: home-control-monitor-st
    spec:
      containers:
      - name: home-control-monitor-st
        image: robjenks/home-control-monitor-agent-st:latest
        ports:
        - name: service-port
          containerPort: 14230
          protocol: TCP
        - name: actuator-port
          containerPort: 14231
          protocol: TCP
        env:
        - name: BOOTSTRAP_SERVERS
          value: http://home-control-kafka-brokers:29092
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: st-auth
              key: internal-token
      nodeSelector:
        host.specs: low
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            entityType: monitor-agent
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
spec:
  selector:
    entity: home-control-monitor-st
  ports:
  - name: service-port
    port: 14230
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14231
    targetPort: actuator-port
    protocol: TCP


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-aggregation-ui
  namespace: home-control
  labels:
    entity: home-control-aggregation-ui
    entityType: aggregation-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-aggregation-ui
  template:
    metadata:
      labels:
        entity: home-control-aggregation-ui
    spec:
      containers:
      - name: home-control-aggregation-ui
        image: robjenks/home-control-aggregation-ui:latest
        ports:
        - name: http-port
          containerPort: 14800
          protocol: TCP
        env:
        - name: AGGREGATION_SERVICE_URL
          value: http://home-control-aggregation:14200
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-aggregation-ui
  namespace: home-control
  labels:
    entity: home-control-aggregation-ui
spec:
  selector:
    entity: home-control-aggregation-ui
  clusterIP: None       # Headless
  ports:
  - name: http-port
    port: 14800
    targetPort: http-port
    protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-control-ingress
  namespace: home-control
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-control-aggregation-ui
            port:
              number: 14800

#---
#kind: Deployment
#apiVersion: apps/v1 
#metadata:
#  name: home-control-ingress
#  labels:
#    app: home-control-ingress
#spec:
#  selector:
#    matchLabels:
#      app: home-control-ingress
#  template:
#    metadata:
#      labels:
#        app: home-control-ingress
#    spec:
#      containers:
#      - name: home-control-ingress
#        image: robjenks/home-control-ingress:latest
#        ports:
#        - name: http-port
#          containerPort: 14800
#        - name: envoy-admin
#          containerPort: 9901
#      nodeSelector:
#        kubernetes.io/arch: arm64       # Currently required; no arm-v7 image for rpi
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: home-control-ingress
#  labels:
#    app: home-control-ingress
#spec:
#  type: ClusterIP
#  ports:
#  - name: http-port
#    port: 14800
#    targetPort: http-port
#    protocol: TCP
#  selector:
#    app: home-control-ingress

