---
kind: Namespace
apiVersion: v1
metadata:
  name: home-control
  labels:
    name: home-control


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
    entityType: aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-aggregation
  template:
    metadata:
      labels:
        entity: home-control-aggregation
    spec:
      containers:
      - name: home-control-aggregation
        image: robjenks/home-control:aggregation-latest
        ports:
        - name: service-port
          containerPort: 14200
          protocol: TCP
        - name: actuator-port
          containerPort: 14201
          protocol: TCP
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-aggregation
  namespace: home-control
  labels:
    entity: home-control-aggregation
spec:
  selector:
    entity: home-control-aggregation
  ports:
  - name: service-port
    port: 14200
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14201
    targetPort: actuator-port
    protocol: TCP
        
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-awair
  template:
    metadata:
      labels:
        entity: home-control-monitor-awair
    spec:
      containers:
      - name: home-control-monitor-awair
        image: robjenks/home-control:monitor-agent-awair-latest
        ports:
        - name: service-port
          containerPort: 14210
          protocol: TCP
        - name: actuator-port
          containerPort: 14211
          protocol: TCP
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-awair
  namespace: home-control
  labels:
    entity: home-control-monitor-awair
spec:
  selector:
    entity: home-control-monitor-awair
  ports:
  - name: service-port
    port: 14210
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14211
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-hue
  template:
    metadata:
      labels:
        entity: home-control-monitor-hue
    spec:
      containers:
      - name: home-control-monitor-hue
        image: robjenks/home-control:monitor-agent-hue-latest
        ports:
        - name: service-port
          containerPort: 14220
          protocol: TCP
        - name: actuator-port
          containerPort: 14221
          protocol: TCP
        env:
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: hue-auth
              key: internal-token
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-hue
  namespace: home-control
  labels:
    entity: home-control-monitor-hue
spec:
  selector:
    entity: home-control-monitor-hue
  ports:
  - name: service-port
    port: 14220
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14221
    targetPort: actuator-port
    protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
    entityType: monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-monitor-st
  template:
    metadata:
      labels:
        entity: home-control-monitor-st
    spec:
      containers:
      - name: home-control-monitor-st
        image: robjenks/home-control:monitor-agent-st-latest
        ports:
        - name: service-port
          containerPort: 14230
          protocol: TCP
        - name: actuator-port
          containerPort: 14231
          protocol: TCP
        env:
        - name: INTERNAL_TOKEN
          valueFrom:
            secretKeyRef:
              name: st-auth
              key: internal-token
      nodeSelector:
        host.specs: low
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-monitor-st
  namespace: home-control
  labels:
    entity: home-control-monitor-st
spec:
  selector:
    entity: home-control-monitor-st
  ports:
  - name: service-port
    port: 14230
    targetPort: service-port
    protocol: TCP
  - name: actuator-port
    port: 14231
    targetPort: actuator-port
    protocol: TCP


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-control-aggregation-ui
  namespace: home-control
  labels:
    entity: home-control-aggregation-ui
    entityType: aggregation-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      entity: home-control-aggregation-ui
  template:
    metadata:
      labels:
        entity: home-control-aggregation-ui
    spec:
      containers:
      - name: home-control-aggregation-ui
        image: robjenks/home-control:aggregation-ui-latest
        ports:
        - name: http-port
          containerPort: 14800
          protocol: TCP
        env:
        - name: AGGREGATION_SERVICE_URL
          value: http://home-control-aggregation:14200
      nodeSelector:
        host.specs: high
  revisionHistoryLimit: 2

---
kind: Service
apiVersion: v1
metadata:
  name: home-control-aggregation-ui
  namespace: home-control
  labels:
    entity: home-control-aggregation-ui
spec:
  selector:
    entity: home-control-aggregation-ui
  ports:
  - name: http-port
    port: 14800
    targetPort: http-port
    protocol: TCP
  type: NodePort

