server:
  port: 14210

management:
  server:
    port: 14211
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

monitor:
  sensors:
    - "http://192.168.1.21"
    - "http://192.168.1.25"
  query: /air-data/latest
  pollIntervalMs: 5000

producer:
  id: awair-agent-producer-01
  config: config/status-monitor-awair-producer.properties

logging:
  level:
    root: INFO
    org.rj: DEBUG
