server:
  port: 10211
management:
  server:
    port: 10212
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
monitor:
  sensors:
    - "http://awair-elem-141ea1.local"
  query: /air-data/latest
  pollIntervalMs: 500
producer:
  id: awair-agent-producer-01
  config: config/status-monitor-awair-producer.properties
