server:
  port: 10210

management:
  server:
    port: 10211
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

monitor:
  sensors:
    - "http://awair-elem-141ea1.local"
    - "http://awair-elem-14356c.local"
  query: /air-data/latest
  pollIntervalMs: 5000

producer:
  id: awair-agent-producer-01
  config: config/status-monitor-awair-producer.properties

logging:
  level:
    root: INFO
    org.rj: DEBUG
