---
version: '3.6'

services:
  home-control-monitor-hue:
    image: robjenks/home-control:monitor-agent-hue-${DEPLOYMENT_VERSION}
    ports:
      - "14220:14220"
      - "14221:14221"
    environment:
      - INTERNAL_TOKEN

