server:
  port: 14200

management:
  server:
    port: 14201
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

aggregation:
  config: config/home-config.yml
  logging:
    logInboundRecords: true
  metrics:
    port: 14202
  metricsMonitor:
    monitoredServices:
      consumer:
        collectionIntervalSecs: 5
    producer:
      id: cluster-metrics-producer-01
      config: config/cluster-metrics-producer.properties

consumer:
  id: status-consumer-01
  config: config/event-consumer.properties
