server:
  port: 14200
management:
  server:
    port: 14201
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
consumer:
  id: status-consumer-01
  config: config/event-consumer.properties