server:
  port: 10200
management:
  server:
    port: 10201
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
consumer:
  id: status-consumer-01
  config: config/event-consumer.properties